version: 2

sources:
  - name: brokerage
    schema: digen
    loader: tpcdi.py

    tables:
      - name: daily_market
      - name: watch_history
      - name: trade
      - name: trade_history
      - name: holding_history
      - name: cash_transaction
      
